### ISSUE TITLE
Nie działa "Odpytywanie"

### ISSUE THREAD

**Issue by rafastryk** [gbbsoft/GbbKSeF2#1]
Przy próbie pobrania faktur sprzedaż lub zakup z zakładki "Odpytywanie" pojawia się błąd

```
HTTP Response: 

KSeF_Online.ApiException`1[KSeF_Online.ExceptionResponse]: Nieprawidłowe wywołanie

Status: 400
Response: 


   at KSeF_Online.Client.Online_query_query_invoiceAsync(Int32 pageSize, Int32 pageOffset, QueryInvoiceRequest body, CancellationToken cancellationToken) in C:\Users\gbbso\OneDrive\Dokumenty\!Projekty\TestKSeF2\TestKSeF2\TestKSeF2\obj\KSeF-onlineClient.cs:line 1366

   at TestKSeF2.MainForm.QueryHeader_button_Click(Object sender, EventArgs e) in C:\Users\gbbso\OneDrive\Dokumenty\!Projekty\TestKSeF2\TestKSeF2\TestKSeF2\MainForm.cs:line 547

```

**Comment by gbbsoft** [comment]
KSeF ciągle się zmienia. Program nie jest aktualizowany do tych zmian. Może wrócę do tematu na początku 2024 roku, jak się wszystko ustabilizuje.
